site/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create', views.create, name='create'),
    path('success_saved', views.success_saved, name='success_saved'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/blog_delete/', views.BlogDeleteView.as_view(), name='blog_delete'),
    path('<int:pk>/blog_update/', views.BlogUpdateView.as_view(), name='blog_update')
]

site/mainPage/urls.py
from django.urls import path
from . import views

app_name = 'mainPage'
urlpatterns = [
    path('', views.index, name='index'),
]

site/mainSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
    path('', include('mainPage.urls')),
    path('blogs/', include('blogs.urls')),

    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                           document_root=settings.MEDIA_ROOT)

site/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('create_form', views.create_form, name='create_form'),
    path('create', views.create, name='create'),
    path('success_saved', views.success_saved, name='success_saved'),
    path('<int:pk>/update_question/', views.QuestionUpdateView.as_view(), name='update_question'),
    path('create_choice', views.ChoiceCreateView.as_view(), name='create_choice'),
    path('<int:pk>/update_choice/', views.ChoiceUpdateView.as_view(), name='update_choice'),
    path('<int:question_id>/question_delete/', views.QuestionDeleteView.as_view(), name='question_delete'),
    path('<int:choice_id>/choice_delete/', views.ChoiceDeleteView.as_view(), name='choice_delete'),
]

site/blogs/models.py
from django.db import models
from django.utils import timezone
import datetime


class Blog(models.Model):
    title = models.CharField(max_length=200, verbose_name="Title")
    content = models.TextField(verbose_name="Content")
    pub_date = models.DateTimeField(default=timezone.now(), verbose_name="Published date")
    image = models.ImageField(upload_to='images/', verbose_name="Image")

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return f'/blogs/{self.id}'

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

site/mainPage/models.py
from django.db import models

# Create your models here.

site/polls/models.py
import datetime
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200, verbose_name="Question")
    pub_date = models.DateTimeField(default=timezone.now(), verbose_name="Published date")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def get_absolute_url(self):
        return f'/polls/{self.id}'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, verbose_name="Question")
    choice_text = models.CharField(max_length=200, verbose_name="Choice")
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    def get_absolute_url(self):
        return f'/polls/'

site/blogs/forms.py
from django.forms import ModelForm
from .models import Blog


class CreateForm(ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'pub_date', 'image']

site/polls/forms.py
from django.forms import ModelForm, TextInput, Textarea, DateTimeField
from .models import Question, Choice
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class CreateForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']


class CreateChoice(ModelForm):
     class Meta:
        model = Choice
        fields = ['choice_text', 'question']

site/blogs/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.views import generic
from django.views.generic import UpdateView, DeleteView

from .forms import CreateForm
from .models import Blog


class IndexView(generic.ListView):
    template_name = 'blogs/index.html'
    context_object_name = 'latest_blog_list'

    def get_queryset(self):
        return Blog.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Blog
    template_name = 'blogs/detail_blog.html'


def create(request):
    error =''
    if request.method == 'POST':
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:success_saved'))
        else:
            error = 'Error'

    form = CreateForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'blogs/create_blog.html', data)


def success_saved(request):
    return render(request, 'blogs/success_saved.html')


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = '/blogs/'
    template_name = 'blogs/delete_blog.html'


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'pub_date', 'image']
    template_name = 'blogs/update_blog.html'

site/mainPage/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'mainPage/index.html')

site/polls/views.py
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.generic import UpdateView, CreateView, DeleteView
from .models import Question, Choice
from .forms import CreateForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class QuestionUpdateView(UpdateView):
    model = Question
    fields = ['question_text']
    template_name = 'polls/question_update_form.html'


class ChoiceUpdateView(UpdateView):
    model = Choice
    fields = ['question', 'choice_text']
    template_name = 'polls/choice_update_form.html'


class ChoiceCreateView(CreateView):
    model = Choice
    fields = ['question', 'choice_text']
    template_name = 'polls/choice_create_form.html'


class QuestionDeleteView(DeleteView):
    model = Question
    pk_url_kwarg = "question_id"
    success_url = '/polls/'
    template_name = 'polls/question_delete_form.html'


class ChoiceDeleteView(DeleteView):
    model = Choice
    pk_url_kwarg = "choice_id"
    success_url = '/polls/'
    template_name = 'polls/choice_delete_form.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "No choice made",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def create_form(request):
    return render(request, 'polls/create_form.html')


def create(request):
    error = ''
    if request.method == 'POST':
        form = CreateForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('polls:success_saved'))
        else:
            error = 'Error'
    form = CreateForm()
    data = {
        'form': form,
        'error': error
    }
    return render(request, 'polls/create.html', data)


def success_saved(request):
    return render(request, 'polls/success_saved.html')

site/blogs/templates/blogs/create_blog.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div>
        <h2 align="center">Creating a blog</h2>
</div>
<form align="center" style="margin-left: 10px; margin-top: 120px" action="{% url 'blogs:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}<br>
        <span>{{ error }}</span>
        <input class="btn btn-primary btn-lg btn-success" type="submit" value="Create" style="width: 100px"/>
</form>

{% endblock %}

site/blogs/templates/blogs/delete_blog.html
{% extends 'polls/navigation.html' %}

{% block content %}

<div>
     <h2 align="center">Deleting a blog</h2><br>
     <h4 align="center" class="p-2">Delete this blog?</h4>
</div>
<form align="center" method="post" enctype="multipart/form-data">
     {% csrf_token %}
     <button class="btn btn-success btn-lg" type="submit"  style="width: 100px; margin-top: 350px">Yes</button>
</form>


{% endblock %}

site/blogs/templates/blogs/detail_blog.html
{% extends 'polls/navigation.html' %}
{% block content %}

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<div style="border: 1px solid #237523; background: #d1f9a0">
    <h1 align="center">
        {{ blog.title }}
</h1></div>

<div class="container" style="position: absolute; top:20%; left:10%">
    <div class="row align-items-start">
        <div class="col">
            <p style="font-size: 11px;"><big><big>{{ blog.content }}</big></big>
            <br>
            <p style="color:green">
                Published date: {{ blog.pub_date }}

        </div>
        <div class="col" style="overflow: hidden">
            <p><img src="{{ blog.image.url }}" height="100%" width="100%"></p>

        </div>
    </div>
</div>
<div style="position:absolute; top: 70%; left: 11%">
    <button class="btn btn-success btn-lg" style="width:150px"
            onclick="document.location='../../blogs/{{ blog.id }}/blog_update/'">Update
    </button>
    <i class="px-2"></i>
    <button class="btn btn-warning btn-lg" style="width:150px"
            onclick="document.location='../../blogs/{{ blog.id }}/blog_delete/'">Delete
    </button>
</div>
{% endblock %}

site/blogs/templates/blogs/index.html
{% extends 'polls/navigation.html' %}

{% block content %}
{% if latest_blog_list %}
<div>
    <h1 align="center" class="p-2 ">Blogs</h1>
</div>
<div style="position:absolute; top:44%; left:37%">
    <ul>
        {% for blog in latest_blog_list %}
        <li>
            <a href="{% url 'blogs:detail' blog.id %}">{{ blog.title }}</a>
        </li>
        {% endfor %}
    </ul>
    <div style="margin-left: 120px">
        <p><a class="btn btn-success btn-lg"
              onclick="document.location='../../blogs/create'">Create blog</a></p>
    </div>
</div>
{% else %}

<div style="border: 1px solid #237523; background: #d1f9a0; position:absolute; top: 30%; left: 36%; width: 400px">
    <h1 align="center">Blogs</h1>
</div>
<h4 align="center" style="margin: 10px; margin-top: 260px">No blogs available
    <p><a class="btn btn-success btn-lg" style="margin: 10px; margin-top: 40px"
          onclick="document.location='../../blogs/create'">Create blog</a></p></h4>
{% endif %}

{% endblock %}

site/blogs/templates/blogs/success_saved.html
{% extends 'polls/navigation.html' %}

{% block content %}

<div style="border: 1px solid #237523; background: #d1f9a0; position:absolute; top: 30%; left: 36%; width: 400px">
    <h2 align="center" class="p-2">Blog success saved</h2>
</div>
    <p align="center"><a class="p-3" href="/blogs" style="position:absolute; top:40%; left:44%">Back to blogs?</a></p>

{% endblock %}

site/blogs/templates/blogs/update_blog.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div>
    <h2 align="center">Updating а blog</h2><br>
</div>
<form align="center" style="margin-left: 10px; margin-top: 150px" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
     <input class="btn btn-primary btn-lg btn-success" type="submit" value="Update" style="width:100px"/>
</form>


{% endblock %}

site/mainPage/templates/mainPage/index.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div class="main2" style="border: 1px solid #237523; background: lime; position:absolute; top: 20%; left: 36%; width: 400px">
    <h1 align="center" style="color: black">Polls and blogs</h1></div>
<div style="position:absolute; top: 35%; left: 39.5%">
    <p align="center"><a align="center" href="/polls" class="btn btn-dark btn-lg"
                         style="height: 50px; width: 300px">Polls</a>
        <p><a href="/blogs" class="btn btn-danger btn-lg" style="height: 50px; width: 300px">Blogs</a></p></p>
</div>

{% endblock %}

site/polls/templates/polls/choice_create_form.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div>
    <h2 align="center">Creating a choice</h2>
</div>
<form align="center" style="margin-top: 250px" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input class="btn btn-primary btn-lg btn-success" type="submit" value="Create" style="width: 100px; margin-top: 10px"/>
</form>
{% endblock %}

site/polls/templates/polls/choice_delete_form.html
{% extends 'polls/navigation.html' %}

{% block content %}

<div style="border: 1px solid #237523; background: #d1f9a0; position:absolute; top: 30%; left: 38%; width: 400px">
    <h2 align="center">Deleting a choice</h2><br>
    <h4 align="center" class="p-2">Delete a choice?</h4>
</div>
<form align="center" method="post">
    {% csrf_token %}
    <button class="btn btn-success btn-lg" type="submit" style="width: 100px; margin-top: 350px">Yes</button>
</form>
{% endblock %}

site/polls/templates/polls/choice_update_form.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div style="border: 1px solid #237523; background: #d1f9a0; position:absolute; top: 30%; left: 38%; width: 400px">
    <h2 align="center">Updating a choice</h2>
</div>
<form style="margin-top: 250px" align="center" method="post">
    {% csrf_token %}
    {{form.as_p}}
     <input class="btn btn-primary btn-lg btn-success" type="submit" value="Update"/>
</form>

{% endblock %}

site/polls/templates/polls/create.html
{% extends 'polls/navigation.html' %}

{% block content %}

<div>
        <h2 align="center">Creating a question</h2>
</div>
<form align="center" style="margin-top: 250px" action="{% url 'polls:create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-primary btn-lg btn-success" type="submit" value="Create"/>
</form>

{% endblock %}

site/polls/templates/polls/create_form.html
{% extends 'polls/navigation.html' %}

{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="" method="post">
        <label for="question_name">New question name: </label>
        <input id="question_name" type="text" name="question_name" value="">
        <input type="submit" value="OK">
    </form>
</body>
</html>
{% endblock %}

site/polls/templates/polls/detail.html
{% extends 'polls/navigation.html' %}

{% block content %}
    <h1 align="center" class="p-2" style="margin-top: 130px">{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form align="center" class = "p-2" action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label style="margin-right: 50px" for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
        <a class="btn btn-success btn-sm"
               onclick="document.location='../../polls/{{ choice.id }}/update_choice'">Update</a>
        <a class="btn btn-warning btn-sm"
               onclick="document.location='../../polls/{{ choice.id }}/choice_delete/'">Delete</a><br><br>
    {% endfor %}
        <p><a class="btn btn-outline-success"
                             onclick="document.location='../../polls/{{ question.id }}/update_question/'">Update question</a>
        <a class="btn btn-outline-warning"
           onclick="document.location='../../polls/{{ question.id }}/question_delete/'">Delete question</a></p>
        <button class="btn btn-primary btn-sm btn-success" type="submit" style="width: 150px">Vote</button>
    </form>
{% endblock %}

site/polls/templates/polls/index.html
{% extends 'polls/navigation.html' %}

{% block content %}
{% if latest_question_list %}
<div>
    <h1 align="center">Questions</h1>
</div>
<div style="position:absolute; top:44%; left:37%">
    <ul>
        {% for question in latest_question_list %}
        <li>
            <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
        </li>
        {% endfor %}
    </ul>
    <div style="margin-left: 70px">
        <a class="btn btn-success btn-sm"
           onclick="document.location='../../polls/create'">Create question</a>
        <a class="btn btn-success btn-sm"
           onclick="document.location='../../polls/create_choice'">Create choice</a></p>
    </div>
</div>

{% else %}
<div>
    <h1 align="center">Questions</h1>
</div>
<h4 align="center" style="margin: 10px; margin-top: 260px">No questions available
    <p><a class="btn btn-success btn-lg" style="margin: 10px; margin-top: 40px"
          onclick="document.location='../../polls/create'">Create question</a></p></h4>
{% endif %}

{% endblock %}

site/polls/templates/polls/navigation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>
        body {
        background: aquamarine;
        }
    </style>
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-success">
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/polls">Polls</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="/blogs">Blogs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

{% block content %}

{% endblock %}
</body>
</html>

site/polls/templates/polls/question_delete_form.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div>
    <h1 align="center">Deleting a question</h1><br>
    <h4 align="center" class="p-2">Delete a question?</h4>
</div>
<form align="center" method="post">
    {% csrf_token %}
    <button class="btn btn-success btn-lg" type="submit" style="width: 100px; margin-top: 350px">Yes</button>
</form>

{% endblock %}

site/polls/templates/polls/question_update_form.html
{% extends 'polls/navigation.html' %}

{% block content %}


<div>
    <h2 align="center">Updating a question</h2>
</div>
<form align="center" style="margin-top: 250px" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-primary btn-lg btn-success" type="submit" style="width: 150px">Update</button>
</form>


{% endblock %}

site/polls/templates/polls/results.html
{% extends 'polls/navigation.html' %}

{% block content %}
<div>
    <h1 align="center">Voting results</h1>
</div>
<h3 align="center" style="margin-left: 10px; margin-top: 230px">{{ question.question_text }}</h3>
<div style="position: absolute; top: 45%; left: 40%">
    <ul>
        {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <p><a href="{% url 'polls:detail' question.id %}" style="margin-top: 80px; margin-left: 30px">Vote again?</a></p>
</div>
{% endblock %}

site/polls/templates/polls/success_saved.html
{% extends 'polls/navigation.html' %}

{% block content %}

<div>
    <h2 align="center" class="p-2">Question success saved</h2>
</div>
    <a class="p-3" href="/polls" style="position:absolute; top:40%; left:43%">Back to questions?</a>


{% endblock %}